// Generated by scripts/optimize-photos.py — do not edit by hand.
// Add photos to public/photos/gallery/, then run: python3 scripts/optimize-photos.py

export type GalleryPhoto = {
  src: string;
  thumb: string;
  width: number;
  height: number;
};

export const galleryPhotos: GalleryPhoto[] = [];
