-- Full admin content columns for site_settings (run after setup-site-settings.sql)
-- File: supabase/patch-site-settings-full-admin.sql

ALTER TABLE public.site_settings
  ADD COLUMN IF NOT EXISTS accent_color text NOT NULL DEFAULT '#bd9c3a',
  ADD COLUMN IF NOT EXISTS about_page_title text NOT NULL DEFAULT 'Our Team',
  ADD COLUMN IF NOT EXISTS about_team_section_title text NOT NULL DEFAULT 'Team members',
  ADD COLUMN IF NOT EXISTS about_meetings_section_title text NOT NULL DEFAULT 'When we meet',
  ADD COLUMN IF NOT EXISTS coaches_page_title text NOT NULL DEFAULT 'Coaches',
  ADD COLUMN IF NOT EXISTS sponsors_page_title text NOT NULL DEFAULT 'Sponsors',
  ADD COLUMN IF NOT EXISTS outreach_page_title text NOT NULL DEFAULT 'Outreach',
  ADD COLUMN IF NOT EXISTS core_values_page_title text NOT NULL DEFAULT 'Core Values',
  ADD COLUMN IF NOT EXISTS join_success_title text NOT NULL DEFAULT 'Message sent',
  ADD COLUMN IF NOT EXISTS join_success_message text NOT NULL DEFAULT 'Thanks for reaching out. A coach will reply within a few days.',
  ADD COLUMN IF NOT EXISTS hero_primary_label text NOT NULL DEFAULT 'Meet the team',
  ADD COLUMN IF NOT EXISTS hero_primary_path text NOT NULL DEFAULT '/about',
  ADD COLUMN IF NOT EXISTS hero_secondary_label text NOT NULL DEFAULT 'Watch season videos',
  ADD COLUMN IF NOT EXISTS hero_secondary_path text NOT NULL DEFAULT '/videos',
  ADD COLUMN IF NOT EXISTS cta_primary_label text NOT NULL DEFAULT 'Calendar',
  ADD COLUMN IF NOT EXISTS cta_primary_path text NOT NULL DEFAULT '/calendar',
  ADD COLUMN IF NOT EXISTS cta_secondary_label text NOT NULL DEFAULT 'Our Team',
  ADD COLUMN IF NOT EXISTS cta_secondary_path text NOT NULL DEFAULT '/about',
  ADD COLUMN IF NOT EXISTS core_values_official_blurb text NOT NULL DEFAULT 'Our community expresses the FIRST philosophies of Gracious Professionalism® and Coopertition® through the FIRST Core Values.',
  ADD COLUMN IF NOT EXISTS season_name text NOT NULL DEFAULT 'BIOGLOW',
  ADD COLUMN IF NOT EXISTS season_playlist_id text NOT NULL DEFAULT 'PLN4Ga33Nt9wI',
  ADD COLUMN IF NOT EXISTS season_playlist_url text NOT NULL DEFAULT 'https://www.youtube.com/playlist?list=PLN4Ga33Nt9wI',
  ADD COLUMN IF NOT EXISTS season_resources_url text NOT NULL DEFAULT 'https://education.lego.com/en-us/first-lego-league/season-materials/#future-edition-3-8',
  ADD COLUMN IF NOT EXISTS season_documents jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS season_videos jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS season_video_groups jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS quick_links jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS gallery_hero_title text NOT NULL DEFAULT 'Photo gallery',
  ADD COLUMN IF NOT EXISTS gallery_hero_description text NOT NULL DEFAULT 'Approved photos from practices, builds, and FLL events.',
  ADD COLUMN IF NOT EXISTS gallery_empty_title text NOT NULL DEFAULT 'No photos yet.',
  ADD COLUMN IF NOT EXISTS gallery_empty_message text NOT NULL DEFAULT 'Share photos below — a coach approves them before they appear here.',
  ADD COLUMN IF NOT EXISTS gallery_share_button_label text NOT NULL DEFAULT 'Share your photos',
  ADD COLUMN IF NOT EXISTS events_hero_title text NOT NULL DEFAULT 'Upcoming meetings',
  ADD COLUMN IF NOT EXISTS events_hero_description text NOT NULL DEFAULT 'Team practice on Sundays and Zoom check-ins on Wednesdays.',
  ADD COLUMN IF NOT EXISTS calendar_hero_title text NOT NULL DEFAULT 'Calendar',
  ADD COLUMN IF NOT EXISTS calendar_hero_description text NOT NULL DEFAULT 'Practices, Zoom calls, and team events.',
  ADD COLUMN IF NOT EXISTS videos_hero_title text NOT NULL DEFAULT 'BIOGLOW videos & resources',
  ADD COLUMN IF NOT EXISTS videos_hero_description text NOT NULL DEFAULT 'Official Future Edition videos and PDFs — notebook, rulebook, missions, rubric, and score sheet.',
  ADD COLUMN IF NOT EXISTS quick_links_hero_title text NOT NULL DEFAULT 'Quick links',
  ADD COLUMN IF NOT EXISTS quick_links_hero_description text NOT NULL DEFAULT 'FIRST LEGO League resources and helpful links for Bits & Bots families.',
  ADD COLUMN IF NOT EXISTS consent_hero_title text NOT NULL DEFAULT 'Photo & Media Consent',
  ADD COLUMN IF NOT EXISTS consent_hero_description text NOT NULL DEFAULT 'Permission for Bits & Bots to share team photos and videos.',
  ADD COLUMN IF NOT EXISTS consent_intro_override text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS consent_terms_override jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS consent_both_parents_note_override text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS consent_success_title text NOT NULL DEFAULT 'Consent saved',
  ADD COLUMN IF NOT EXISTS consent_success_message text NOT NULL DEFAULT 'Thank you. Coaches have your signed permission on file.',
  ADD COLUMN IF NOT EXISTS assignments_intro text NOT NULL DEFAULT 'Sign in with your team password to view and submit assignments.',
  ADD COLUMN IF NOT EXISTS generic_coach_bio text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS generic_member_bio text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS footer_meet_team_label text NOT NULL DEFAULT 'Meet our team';

-- Page hero columns (may already exist from patch-site-settings-page-heroes.sql)
ALTER TABLE public.site_settings
  ADD COLUMN IF NOT EXISTS about_hero_description text,
  ADD COLUMN IF NOT EXISTS coaches_hero_description text,
  ADD COLUMN IF NOT EXISTS sponsors_hero_description text,
  ADD COLUMN IF NOT EXISTS outreach_hero_description text,
  ADD COLUMN IF NOT EXISTS join_hero_description text,
  ADD COLUMN IF NOT EXISTS brand_color text NOT NULL DEFAULT '#1f3d1f';
