-- Run once in Supabase SQL Editor to add Troop 2001 Eagle Scout roster (approved).
-- https://supabase.com/dashboard/project/xohaeezxzbeyzpjbngkj/sql/new
--
-- Safe to re-run: skips rows that already exist with the same year + name.

INSERT INTO public.eagle_scouts (year, name, project, status)
SELECT v.year, v.name, v.project, 'approved'::public.content_status
FROM (VALUES
  ('2004', 'Kyle Randolph', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2006', 'Zachary Johnson', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2006', 'David Alpert', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2007', 'Joseph Coleman', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2007', 'Zach Lombardo', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2007', 'Jonathon Janasik', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2007', 'Sebastian Bickford', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2008', 'Michael Sell', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2008', 'Matthew Berning', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2008', 'Cameron Woodward', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2008', 'Thomas Defranchesco', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2008', 'Ajax Abernathy', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2008', 'David Bianchi', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2008', 'Michael Treiser', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2008', 'Robert Koehler', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2009', 'David Chauvette', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2009', 'Jon Coulter', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2009', 'Tyler Paine', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2009', 'Wesley Finger', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2010', 'Daniel Evans', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2010', 'Sean Treiser', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2010', 'Austin Guhl', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2010', 'Graham Woodward', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2010', 'Adren Hance', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2011', 'Thomas Ansley', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2011', 'Dylan Fite', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2011', 'Cash Anthony', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2011', 'Kenny Peredo', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2012', 'Danny Garren', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2012', 'Nick McNamara', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2012', 'Adam Robair', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2012', 'Travers Landreth', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2012', 'Kelby Fruecht', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2013', 'David Kisner', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2013', 'Matthew Paine', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2013', 'Kyle Henning', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2013', 'Chas Tatigian', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2014', 'Blake Holloway', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2014', 'Michael Robair', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2015', 'Jacob Ryan', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2015', 'Tristan Rosal', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2015', 'Colton Guhl', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2015', 'Reems Landreth', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2015', 'Jack Henning', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2015', 'Kyle Kerskie', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2015', 'Max Goin', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2016', 'David Rose', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2016', 'Andrew Mizell', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2016', 'Luke Henning', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2016', 'Jack Arsenau', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2016', 'Dominic DeMarco', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2016', 'Tyler Krawec', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2016', 'Justin Fales', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2016', 'Corbin Summers', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2016', 'Bradley Cunningham', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2016', 'Blake Anderson', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2016', 'Robert Beatty', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2017', 'Kyle Badge', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2017', 'Efehan Timur', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2017', 'Marcello Musca', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2017', 'Matthew Parker', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2018', 'Garrett Arsenault', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2018', 'Adam Glisson', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2018', 'Brandon Gendron', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2018', 'Abhijith Neelamchalil', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2018', 'Michael Mizell', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2018', 'Eli Bickford', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2018', 'Bradley Walters', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2018', 'Joseph Compitello', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2018', 'Ryan Garry', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2019', 'Evan Pasqua', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2019', 'Charles Elam', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2019', 'Nick Nici', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2019', 'RJ Fritz', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2019', 'Gareth Rosal', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2019', 'Michele Santorsola', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2019', 'DeMario Brody-Harris', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2019', 'Morgan Bock', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2020', 'Jack Compitello', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2020', 'Colin Gerlach', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2020', 'Tristan Bashaw', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2020', 'Lucas Bradshaw', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2020', 'Lucca DeMarco', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2020', 'Alex Aristizabal', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2020', 'Jack Carlsen', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2020', 'Trey Connor', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2020', 'Thomas Beatty', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2021', 'Eli Ritter', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2021', 'Lucas Nici', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2021', 'Matthew Glander', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2021', 'Charlie Arseneau', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2021', 'Adam Blais', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2022', 'Jac Callahan', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2022', 'Joe Ritter', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2022', 'Thor Warnken', 'Eagle Scout service project — placeholder text to be updated.'),
  ('2023', 'Rylan Zurbrigg', 'Eagle Scout service project — placeholder text to be updated.')
) AS v(year, name, project)
WHERE NOT EXISTS (
  SELECT 1
  FROM public.eagle_scouts e
  WHERE e.year = v.year AND e.name = v.name
);
