"""Compress site photos in public/photos and write WebP versions for content images.

Also builds the gallery: photos dropped into public/photos/gallery/ get a full-size
and a thumbnail version, and src/lib/gallery-photos.ts is regenerated so the
/gallery page picks them up without any hand-editing.

Originals are copied to photo-originals/ (outside public/, so they are never deployed).
Re-running is safe: the backup is only written the first time a file is seen.

Usage: python3 scripts/optimize-photos.py
"""

import shutil
from pathlib import Path
from urllib.parse import quote

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
PHOTOS = ROOT / "public" / "photos"
BACKUP = ROOT / "photo-originals"
GALLERY = PHOTOS / "gallery"
GALLERY_MANIFEST = ROOT / "src" / "lib" / "gallery-photos.ts"

# path suffix -> (max dimension, output format, quality)
RULES = [
    ("hero/", 2400, "webp", 82),
    ("Outdoor Adventure/", 1600, "webp", 82),
    ("The Trail to Eagle/", 1600, "webp", 82),
    ("values/", 1400, "webp", 80),
    ("events/", 1400, "webp", 80),
    ("gallery/", 1800, "webp", 82),
    ("scoutmasters/", 1000, "jpeg", 80),
]

SKIP = {"favicon-16x16.png", "favicon-32x32.png", "apple-touch-icon.png", "og-logo.png"}

THUMB_SUFFIX = "-thumb"
THUMB_MAX = 800
THUMB_QUALITY = 78


def rule_for(rel: str):
    for prefix, max_dim, fmt, quality in RULES:
        if rel.startswith(prefix):
            return max_dim, fmt, quality
    return None


def backup(path: Path) -> None:
    dest = BACKUP / path.relative_to(PHOTOS)
    if dest.exists():
        return
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(path, dest)


def resized(img: Image.Image, max_dim: int) -> Image.Image:
    if max(img.size) <= max_dim:
        return img
    scale = max_dim / max(img.size)
    return img.resize((round(img.width * scale), round(img.height * scale)), Image.Resampling.LANCZOS)


def already_optimized(path: Path, rel: str, max_dim: int, fmt: str) -> bool:
    """Skip files a previous run already handled, so repeat runs don't re-compress."""
    expected_suffix = ".webp" if fmt == "webp" else path.suffix.lower()
    if path.suffix.lower() != expected_suffix:
        return False
    if max(Image.open(path).size) > max_dim:
        return False
    if rel.startswith("gallery/"):
        return path.with_name(f"{path.stem}{THUMB_SUFFIX}.webp").exists()
    return True


def natural_key(path: Path):
    """Sort 'Gallery 2' before 'Gallery 10' instead of alphabetically."""
    parts = []
    digits = ""
    for char in path.stem:
        if char.isdigit():
            digits += char
        else:
            if digits:
                parts.append((1, int(digits), ""))
                digits = ""
            parts.append((0, 0, char.lower()))
    if digits:
        parts.append((1, int(digits), ""))
    return parts


def prune_orphan_thumbs() -> int:
    """Delete thumbnails whose full-size photo was removed from the gallery folder."""
    removed = 0
    for thumb in GALLERY.glob(f"*{THUMB_SUFFIX}.webp"):
        if not thumb.with_name(f"{thumb.stem[: -len(THUMB_SUFFIX)]}.webp").exists():
            thumb.unlink()
            removed += 1
    return removed


def write_gallery_manifest() -> int:
    """Regenerate src/lib/gallery-photos.ts from whatever is in public/photos/gallery/."""
    entries = []
    for path in sorted(GALLERY.glob("*.webp"), key=natural_key):
        if path.stem.endswith(THUMB_SUFFIX):
            continue
        thumb = path.with_name(f"{path.stem}{THUMB_SUFFIX}.webp")
        width, height = Image.open(path).size
        entries.append(
            {
                "src": "/photos/gallery/" + quote(path.name),
                "thumb": "/photos/gallery/" + quote(thumb.name if thumb.exists() else path.name),
                "width": width,
                "height": height,
            }
        )

    lines = [
        "// Generated by scripts/optimize-photos.py — do not edit by hand.",
        "// Add photos to public/photos/gallery/, then run: python3 scripts/optimize-photos.py",
        "",
        "export type GalleryPhoto = {",
        "  src: string;",
        "  thumb: string;",
        "  width: number;",
        "  height: number;",
        "};",
        "",
        "export const galleryPhotos: GalleryPhoto[] = [",
    ]
    for entry in entries:
        lines.append(
            f'  {{ src: "{entry["src"]}", thumb: "{entry["thumb"]}", '
            f'width: {entry["width"]}, height: {entry["height"]} }},'
        )
    lines += ["];", ""]

    GALLERY_MANIFEST.write_text("\n".join(lines))
    return len(entries)


def main() -> None:
    before = after = 0

    for path in sorted(PHOTOS.rglob("*")):
        if path.suffix.lower() not in {".png", ".jpg", ".jpeg", ".webp"} or path.name in SKIP:
            continue
        if path.stem.endswith(THUMB_SUFFIX):
            continue

        rel = str(path.relative_to(PHOTOS))
        original_size = path.stat().st_size
        before += original_size

        if path.name == "Logo.png":
            backup(path)
            img = resized(Image.open(path).convert("RGBA"), 512)
            img.save(path, format="PNG", optimize=True)
            after += path.stat().st_size
            print(f"{rel}: {original_size/1024/1024:.2f} MB -> {path.stat().st_size/1024/1024:.2f} MB")
            continue

        rule = rule_for(rel)
        if rule is None:
            after += original_size
            continue

        max_dim, fmt, quality = rule

        if already_optimized(path, rel, max_dim, fmt):
            after += original_size
            continue

        backup(path)
        img = resized(Image.open(path), max_dim)

        if fmt == "webp":
            out = path.with_suffix(".webp")
            img.save(out, format="WEBP", quality=quality, method=6)
            if out != path:
                path.unlink()
        else:
            out = path
            img.convert("RGB").save(out, format="JPEG", quality=quality, optimize=True, progressive=True)

        new_size = out.stat().st_size

        if rel.startswith("gallery/"):
            thumb_path = out.with_name(f"{out.stem}{THUMB_SUFFIX}.webp")
            resized(img, THUMB_MAX).save(
                thumb_path, format="WEBP", quality=THUMB_QUALITY, method=6
            )
            new_size += thumb_path.stat().st_size

        after += new_size
        print(f"{rel} -> {out.name}: {original_size/1024/1024:.2f} MB -> {new_size/1024/1024:.2f} MB")

    orphans = prune_orphan_thumbs()
    if orphans:
        print(f"\nRemoved {orphans} leftover thumbnail(s) for deleted photos")

    count = write_gallery_manifest()
    print(f"\nGallery: {count} photo(s) written to {GALLERY_MANIFEST.relative_to(ROOT)}")
    print(f"Total: {before/1024/1024:.1f} MB -> {after/1024/1024:.1f} MB")


if __name__ == "__main__":
    main()
